apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-airflow-k8s
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.36.6.1
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-airflow-k8s
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: "pv-airflow-k8s"